version: "3.9"
services:
  mssql:
    hostname: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Qwert12345"
    ports:
      - "14333:1433"

  api:
    hostname: api
    image: bookstore_img:latest
    depends_on:
      - mssql
    ports:
      - "8080:80"
